apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: helmfile
spec:
  version: v1.0
  generate:
    command: ["sh", "-c"]
    args:
      - helmfile -n "$ARGOCD_APP_NAMESPACE" template --include-crds -q
  discover:
    fileName: "./helmfile.yaml"
